In [1]:
import pandas as pd
import os, sys

In [5]:
base_dir = "/Users/andrew/Desktop/Harvard/idreos-research/mem-run-estimator/final_models"
file = os.path.join(base_dir, "conv.csv")
df = pd.read_csv(file)
df

,batch_size,in_channels,iH,iW,out_channels,groups,kH,kW,stride,padding,dilation,transposed,bias
0,64,3,224,224,352,1,4,4,"(4, 4)","[0, 0]","(1, 1)",False,True
1,64,352,56,56,352,352,7,7,"(1, 1)","[3, 3]","(1, 1)",False,True
2,64,352,56,56,704,1,2,2,"(2, 2)","[0, 0]","(1, 1)",False,True
3,64,704,28,28,704,704,7,7,"(1, 1)","[3, 3]","(1, 1)",False,True
4,64,704,28,28,1408,1,2,2,"(2, 2)","[0, 0]","(1, 1)",False,True
5,64,1408,14,14,1408,1408,7,7,"(1, 1)","[3, 3]","(1, 1)",False,True
6,64,1408,14,14,2816,1,2,2,"(2, 2)","[0, 0]","(1, 1)",False,True
7,64,2816,7,7,2816,2816,7,7,"(1, 1)","[3, 3]","(1, 1)",False,True
8,64,3,224,224,1280,1,14,14,"(14, 14)","[0, 0]","(1, 1)",False,NaN

In [10]:
df.describe()

,batch_size,in_channels,iH,iW,out_channels,groups,kH,kW
count,9.0,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000
mean,64.0,861.111111,72.333333,72.333333,1315.555556,587.222222,5.777778,5.777778
std,0.0,898.626096,87.709749,87.709749,943.789054,963.611407,3.865805,3.865805
min,64.0,3.000000,7.000000,7.000000,352.000000,1.000000,2.000000,2.000000
25%,64.0,352.000000,14.000000,14.000000,704.000000,1.000000,2.000000,2.000000
50%,64.0,704.000000,28.000000,28.000000,1280.000000,1.000000,7.000000,7.000000
75%,64.0,1408.000000,56.000000,56.000000,1408.000000,704.000000,7.000000,7.000000
max,64.0,2816.000000,224.000000,224.000000,2816.000000,2816.000000,14.000000,14.000000

In [6]:
df["groups"].value_counts()

groups
1       5
352     1
704     1
1408    1
2816    1
Name: count, dtype: int64

In [8]:
df.query("iH != iW")

Empty DataFrame
Columns: [batch_size, in_channels, iH, iW, out_channels, groups, kH, kW, stride, padding, dilation, transposed, bias]
Index: []

In [9]:
df.query("kH != kW")

Empty DataFrame
Columns: [batch_size, in_channels, iH, iW, out_channels, groups, kH, kW, stride, padding, dilation, transposed, bias]
Index: []